---
hostname: tower.example.net
awx_branch: 9.0
awx_path:  /srv/ansible/awx
awx_selinux: false  ## As of 2.9.1 there are bugs in semanage and seports.

admin:
  user: admin
  email: admin@example.net

nginx:
  ### ClearLinux
  #configpath: /usr/share/nginx/conf
  ### Fedora
  hostname: tower.example.net
  configpath: /etc/nginx
  cert_name: fullchain.pem
  key_name: privkey.pem
  user: nginx
  group: nginx
  default_ssl: True  ## install a http->https default server template

certbot:
  ## if this is defined, it will create a test cert
  #test: True
  hostname: tower.example.net
  pyvenv: /usr/local/certbot
  aws_access_key_id: XXXXXXXXXXXXXXXXXX
  aws_secret_access_key: YYYYYYYYYYYYYYYYYYY
  acme_email: user@example.net
  aliases:
    - alias.example.net

awx_user:
  user: ansible
  group: wheel
  uid:   770
  gid:   770
  home: /srv/ansible
  bindir: /srv/ansible/bin
  pgdb: awx
  pguser: awx

admin_users:
  - eis

awx_packages:
  - krb5-devel
  - libcurl-devel
  - libffi-devel
  - libpq-devel
  - libtool-ltdl-devel
  - libxslt-devel
  - memcached
  - npm
  - openldap-devel
  - postgresql
  - postgresql-plpython3
  - postgresql-server
  - postgresql-devel
  - python3-devel
  - python3-psycopg2
  - sshpass
  - subversion
  - xmlsec1-devel
  - xmlsec1-openssl-devel

firewallports:
  - https
  - http
  - ssh

seports:
  - '8050'
  - '8051'
  - '8052'
  - '443'
  - '80'

services:
  - awx-cbreceiver.service
  - awx-channels-worker.service
  - awx-daphne.service
  - awx-dispatcher.service
  - awx-web.service
  - awx.service

repos:
  - rabbitmq-erlang.repo
  - rabbitmq.repo

deploymentfolders:
  - /var/lib/awx
  - /usr/share/awx
