---
- name: AWX Systemd configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: '0644'
    owner: root
    group: root
  loop: "{{ services }}"

- name: AWX Tower Config Folder
  file:
    path: /etc/tower
    state: directory
    mode: '0755'
    owner: "{{ awx_user['user'] }}"
    group: "{{ awx_user['group'] }}"
    setype: system_conf_t

- name: Services Schedule for startup / Start
  systemd:
    state:   started
    name:    "{{ item }}"
    masked:  no
    enabled: yes
    daemon_reload: yes
  loop: "{{ services }}"
