---
- name: Deploy NGINX and Ansible AWX Locally
  hosts: all
  remote_user: localuser
  # remote_user: user
  become: yes
  become_method: sudo

  roles:
    - common
    - emacs_text
    - certbot
    - nginx
    - awx-base
    - awx-dbsetup
    - awx-repo
    - awx-install
    - awx-services