---
- name: Reset Working Folder Permissions
  file:
    dest: "{{ awx_path }}"
    owner: "{{ awx_user['user'] }}"
    group: "{{ awx_user['group'] }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Git Repo Checkout/Update
  git:
    repo: https://github.com/ansible/awx.git
    dest: "{{ awx_path }}"
    version: "devel"
    force: yes

- name: Locate Latest Tagged Release
  shell: |
    set -o pipefail
    git rev-list -n 1 `sudo git tag |grep {{ awx_branch }}|tail -n 1`
  args:
    chdir: "{{ awx_path }}"
  register: latest_tag
  when: latest_tag is undefined

- name: Switch to Tagged Release
  git:
    repo: https://github.com/ansible/awx.git
    dest: "{{ awx_path }}"
    version: "{{ latest_tag.stdout }}"
    force: yes

# - name: AWX Copy Static Files
#   shell: |
#     set -o pipefail
#     cp -ar ui/client/assets/logo-header.svg /opt/awx/static/assets/
#     cp -ar ui/client/assets/logo-login.svg /opt/awx/static/assets/
#   args:
#     chdir: "{{ awx_path }}"
